### ISSUE TITLE
Fix running from command line

### ISSUE THREAD

**Issue by MotaDan** [MotaDan/steganographerPY#34]
After installing with pip, I can not run steganographer from the command line. I am given this error.

C:\Users\Daniel>steganographer
Traceback (most recent call last):
  File "c:\users\daniel\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\daniel\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python35-32\Scripts\steganographer.exe\__main__.py", line 5, in <module>
ImportError: cannot import name 'main'

**Comment by MotaDan** [comment]
Probable solution
[Python Apps the Right Way: entry points and scripts](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/)

**Comment by MotaDan** [comment]
Fixed as of 1.0.1
