### ISSUE TITLE
Fix crashes when installing from pip

### ISSUE THREAD

**Issue by MotaDan** [MotaDan/steganographerPY#40]
When installed on not my computer trying to run after installing from pip caused and error. The -h option did not work and there was a stack trace.

**Comment by MotaDan** [comment]
Could not reproduce on my computer directly or by using virtuaenv as a fresh python install. Removing from milestone for now until I have a chance to investigate directly.

**Comment by MotaDan** [comment]
Used [Tox](http://docs.pytest.org/en/latest/goodpractices.html#use-tox) and still can't get a failure.

**Comment by MotaDan** [comment]
I upgraded to 1.0.2 on the effected computer and still get this error.

> Traceback (most recent call last):
>   File "c:\users\alexi\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\alexi\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\alexi\AppData\Local\Programs\Python\Python35-32\Scripts\steganographer.exe\__main__.py", line 5, in <module>
> ImportError: No module named 'steganographer.__main__'

**Comment by MotaDan** [comment]
Uninstalling and reinstalling seems to have fixed it. No clue what happened originally.
